import * as M from '..';
import * as P from './core';
export declare const language: {
    fullParser: P.Parser<(string | M.MfmNode)[]>;
    simpleParser: P.Parser<(string | M.MfmSimpleNode)[]>;
    full: P.Parser<string | M.MfmNode>;
    simple: P.Parser<string | M.MfmSimpleNode>;
    inline: P.Parser<string | M.MfmInline>;
    quote: P.Parser<M.MfmQuote>;
    codeBlock: P.Parser<M.MfmCodeBlock>;
    mathBlock: P.Parser<M.MfmMathBlock>;
    centerTag: P.Parser<M.MfmCenter>;
    big: P.Parser<string | M.MfmFn>;
    boldAsta: P.Parser<string | M.MfmBold>;
    boldTag: P.Parser<string | M.MfmBold>;
    boldUnder: P.Parser<M.MfmBold>;
    smallTag: P.Parser<string | M.MfmSmall>;
    italicTag: P.Parser<string | M.MfmItalic>;
    italicAsta: P.Parser<M.MfmItalic>;
    italicUnder: P.Parser<M.MfmItalic>;
    strikeTag: P.Parser<string | M.MfmStrike>;
    strikeWave: P.Parser<string | M.MfmStrike>;
    unicodeEmoji: P.Parser<M.MfmUnicodeEmoji>;
    plainTag: P.Parser<M.MfmPlain>;
    fn: P.Parser<string | M.MfmFn>;
    inlineCode: P.Parser<M.MfmInlineCode>;
    mathInline: P.Parser<M.MfmMathInline>;
    mention: P.Parser<string | M.MfmMention>;
    hashtag: P.Parser<M.MfmHashtag>;
    emojiCode: P.Parser<M.MfmEmojiCode>;
    link: P.Parser<M.MfmLink>;
    url: P.Parser<string | M.MfmUrl>;
    urlAlt: P.Parser<M.MfmUrl>;
    search: P.Parser<M.MfmSearch>;
    text: P.Parser<string>;
};
